### ISSUE TITLE
misplaced type annotation error with PyLint

### ISSUE THREAD

**Issue by c22** [alexa/skill-sample-python-helloworld-decorators#4]
PyLint complains that the type annotations in hello_world.py are misplaced.

To reproduce, run PyLint against the hello world example, you will see a PyLint error along the lines of:
```
************* Module skill
skill.py:23:0: E0001: misplaced type annotation (<unknown>, line 23) (syntax-error)
```

Seems like these kinds of entries:

```
@sb.request_handler(can_handle_func=is_request_type("LaunchRequest"))
def launch_request_handler(handler_input):
    """Handler for Skill Launch."""
    # type: (HandlerInput) -> Response
    speech_text = "Welcome to the Alexa Skills Kit, you can say hello!"

    return handler_input.response_builder.speak(speech_text).set_card(
        SimpleCard("Hello World", speech_text)).set_should_end_session(
        False).response
```

Should really be like:

```
@sb.request_handler(can_handle_func=is_request_type("LaunchRequest"))
def launch_request_handler(handler_input: HandlerInput) -> Response:
    """Handler for Skill Launch."""
    speech_text = "Welcome to the Alexa Skills Kit, you can say hello!"

    return handler_input.response_builder.speak(speech_text).set_card(
        SimpleCard("Hello World", speech_text)).set_should_end_session(
        False).response
```

At least according to my understanding of [PEP-484](https://www.python.org/dev/peps/pep-0484/).

Note that this also seems to affect the class based hello world as well:
https://github.com/alexa/skill-sample-python-helloworld-classes

I don't mind submitting a PR for these changes, but I am not sure if these examples are automatically generated by a model somewhere, in which case it might be better to update the model upstream instead.

**Comment by aszk** [comment]
Thank you for your feedback. I believe we chose `# type:` for backward compatibility for Python 2.x. Please see [here](https://peps.python.org/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code) I understand this is not relevant anymore however we don't have a plan to update it to type hint annotation since it doesn't affect skill's behavior. We will think updating our guideline for the future repositories.
