### ISSUE TITLE
'handler' should be 'lambda_handler' in hello_world.py ?

### ISSUE THREAD

**Issue by hqm** [alexa/skill-sample-python-helloworld-decorators#6]
handler = sb.lambda_handler()

I think the above line in hello_world.py:102 example should be

lambda_handler = sb.lambda_handler()

Otherwise I get this error when running the code in Lambda:

20:39:33
[ERROR] Runtime.HandlerNotFound: Handler 'lambda_handler' missing on module 'lambda_function'
[ERROR] Runtime.HandlerNotFound: Handler 'lambda_handler' missing on module 'lambda_function'

**Comment by nicosingh** [comment]
I had the same issue, but changing the variable name from `handler` to `lambda_handler` saved my day. Thanks for that 😊

**Comment by aszk** [comment]
This is because the [instruction](https://github.com/alexa-samples/skill-sample-python-helloworld-decorators/blob/master/instructions/2-lambda-function.md) updates handler name to hello_world.handler on 7 - vi. If you want to use default handler name, you need to update the code to lambda_handler.
